### ISSUE TITLE
全文检索使用哪个框架呢？

### ISSUE THREAD

**Issue by Sod-Momas** [yanglbme/qa#4]
是用最近火起来的ES还是老牌solr?
或者有更好的选择？

**Comment by yanglbme** [comment]
打算使用Solr7.3呢

**Comment by wangliguo123321** [comment]
面试被问到：站内全文搜索， 除了solar还有其他的吗？为什么选择solar？

**Comment by yanglbme** [comment]
@wangliguo123321 看来应该仔细研究一下 es 和 solr 的优劣~

**Comment by wangliguo123321** [comment]
是的是的， 老哥有没有想法把网站部署一波啊；

**Comment by yanglbme** [comment]
@wangliguo123321 哈哈哈，目前暂时没考虑买虚拟机或者云服务器...
